apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: sunbird-mcp-server
  name: sunbird-mcp-server
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sunbird-mcp-server:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: JSDuHowU4ZZZYfatttYM
    type: GitHub
  - generic:
      secret: 2TRKM6EP-tvwTLz1-l1k
    type: Generic
