apiVersion: v1
kind: Service
metadata:
  labels:
    app: dctrack-chat-ui
  name: dctrack-chat-ui
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dctrack-chat-ui
  sessionAffinity: None
  type: ClusterIP
