apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: sunbird-mcp-build
  name: sunbird-mcp-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sunbird-mcp-build:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 0WhwZCwUF9z-25xZJkhw
    type: GitHub
  - generic:
      secret: yRHYvhqPOoBG2KFCyhYP
    type: Generic
